In [2]:
import numpy as np

# Why to use Numpy!
# 1. single data type
# 2. N dimensional arrrays
# 3. Performance - loops(avoid!) -> inbuilt numpy aggregations and functions
# 4. Excellent documentation

In [3]:
# integer array:
a = np.array([1, 4, 2, 5, 3])
print(type(a))

<class 'numpy.ndarray'>


In [5]:
# Upcasting
np.array([3, "4", True, False,1.3])

array(['3', '4', 'True', 'False', '1.3'], dtype='<U21')

In [30]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
# Create a 3x5 floating-point array filled with 1s
np.ones((3, 5), dtype=float)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [7]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [8]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [33]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [10]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.12617113, 0.54317145, 0.94867775],
       [0.8491413 , 0.71416541, 0.49052684],
       [0.96553491, 0.91093149, 0.06707574]])

In [11]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-0.14488768, -2.20326011,  0.51769018],
       [-0.94010518,  0.18189845,  0.73070986],
       [-0.07166491,  2.34903898,  0.890852  ]])

In [36]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[7, 3, 8],
       [3, 0, 8],
       [6, 3, 3]])

In [13]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that
# memory location
np.empty(30)

array([6.93278718e-310, 4.65879565e-310, 0.00000000e+000, 0.00000000e+000,
       6.93277245e-310, 4.82337433e+228, 6.14415221e-144, 1.16097020e-028,
       7.25380095e-043, 2.73540465e-052, 2.58453061e-057, 3.97062373e+246,
       1.16318408e-028, 3.99839965e+175, 4.39659746e+175, 6.59103200e-066,
       5.44418136e-062, 5.04621361e+180, 8.37170571e-144, 4.32090821e-096,
       6.32299154e+233, 6.48224638e+170, 2.20791404e+214, 3.83819517e+151,
       3.75919017e+179, 2.80066088e-032, 9.23113419e-071, 4.75471411e+174,
       7.06271461e-071, 6.93287617e-310])

In [46]:
myArray = np.arange(1,10,2)

In [47]:
print(myArray)

[1 3 5 7 9]


In [48]:
print(myArray[0])

1


In [49]:
print(myArray[2:5])

[5 7 9]


In [8]:
# Create an identity matrix
# Add 1 to all cells
a = np.identity(4) + 1

# write an example of reshape on this identity matrix

In [9]:
print(np.shape(a))
print(a)

(4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [62]:
np.reshape(a,(2, 8))

array([[2., 1., 1., 1., 1., 2., 1., 1.],
       [1., 1., 2., 1., 1., 1., 1., 2.]])

In [63]:
np.ndarray.flatten(a)

array([2., 1., 1., 1., 1., 2., 1., 1., 1., 1., 2., 1., 1., 1., 1., 2.])

In [71]:
d = np.arange('2002-10-27T04:30', 40*60, 60, dtype='M8[s]')
print(d)
d = np.arange('2002-10-27T04:30', 4*60, 60, dtype='M8[m]')
print(d)

['2002-10-27T04:30:00' '2002-10-27T04:31:00' '2002-10-27T04:32:00'
 '2002-10-27T04:33:00' '2002-10-27T04:34:00' '2002-10-27T04:35:00'
 '2002-10-27T04:36:00' '2002-10-27T04:37:00' '2002-10-27T04:38:00'
 '2002-10-27T04:39:00' '2002-10-27T04:40:00' '2002-10-27T04:41:00'
 '2002-10-27T04:42:00' '2002-10-27T04:43:00' '2002-10-27T04:44:00'
 '2002-10-27T04:45:00' '2002-10-27T04:46:00' '2002-10-27T04:47:00'
 '2002-10-27T04:48:00' '2002-10-27T04:49:00' '2002-10-27T04:50:00'
 '2002-10-27T04:51:00' '2002-10-27T04:52:00' '2002-10-27T04:53:00'
 '2002-10-27T04:54:00' '2002-10-27T04:55:00' '2002-10-27T04:56:00'
 '2002-10-27T04:57:00' '2002-10-27T04:58:00' '2002-10-27T04:59:00'
 '2002-10-27T05:00:00' '2002-10-27T05:01:00' '2002-10-27T05:02:00'
 '2002-10-27T05:03:00' '2002-10-27T05:04:00' '2002-10-27T05:05:00'
 '2002-10-27T05:06:00' '2002-10-27T05:07:00' '2002-10-27T05:08:00'
 '2002-10-27T05:09:00']
['2002-10-27T04:30' '2002-10-27T05:30' '2002-10-27T06:30'
 '2002-10-27T07:30']


In [69]:
print(d)

['2002-10-27T04:30' '2002-10-27T05:30' '2002-10-27T06:30'
 '2002-10-27T07:30']


In [ ]:
# HW - load and save function in numpy

In [13]:
a = np.arange(6).reshape(2,3)
for x in np.nditer(a, order='F'):
    print(x, end=' ')

0 3 1 4 2 5 

In [73]:
a = np.arange(6).reshape(2,3)
for x in np.nditer(a):
    print(x, end=' ')

0 1 2 3 4 5 

In [14]:
print(a)

[[0 1 2]
 [3 4 5]]


In [75]:
np.floor([1.2])

array([1.])

In [76]:
np.sum(a)

15

In [77]:
print(a)

[[0 1 2]
 [3 4 5]]


In [10]:
a = np.array([[1, 1], [1, np.nan]])

In [11]:
print(a)

[[ 1.  1.]
 [ 1. nan]]


In [81]:
print(np.sum(a))
print(np.nansum(a))

nan
3.0


In [ ]:
# HW - load and save function in numpy
# HW - broadcast in numpy
# HW - Read chapter on pandas